name: Sync fork with upstream

on:
  schedule:
    - cron: "0 1 * * *" # 每天 UTC 1 点（北京 9 点）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge upstream
        run: |
          git remote add upstream https://github.com/Nshpiter/HuaweiPods.git
          git fetch upstream main
          git config user.name "Wanghn233"
          git config user.email "30120785+Wanghn233@users.noreply.github.com"
          git merge upstream/main --no-edit
          git push origin main
